/* ===========================
   Modal Controls
   =========================== */
function openPurchaseModal() {
  document.getElementById("purchaseModal").style.display = "block";
}
function closePurchaseModal() {
  document.getElementById("purchaseModal").style.display = "none";
}

function openVerificationModal() {
  document.getElementById("verificationModal").style.display = "block";
}
function closeVerificationModal() {
  document.getElementById("verificationModal").style.display = "none";
}

/* ===========================
   Autogenerated User Number
   =========================== */
function generateUserNumber() {
  // Example: random 5-digit number
  return Math.floor(10000 + Math.random() * 90000);
}

/* ===========================
   Purchase Flow
   =========================== */
function processPurchase() {
  const fullName = document.getElementById("fullName").value.trim();
  const email = document.getElementById("email").value.trim();
  const contactNumber = document.getElementById("contactNumber").value.trim();
  const paymentMethod = document.getElementById("paymentMethod").value;

  if (!fullName || !email || !contactNumber) {
    alert("Please complete all required fields.");
    return;
  }

  // Generate user number + verification code
  const userNumber = generateUserNumber();
  const baseCode = "CCMHP-36912-2025-0777";
  const verificationCode = `${baseCode}${userNumber}`;

  // Store values for later use (certificate generation, verification modal)
  localStorage.setItem("userNumber", userNumber);
  localStorage.setItem("verificationCode", verificationCode);
  localStorage.setItem("fullName", fullName);

  // Redirect to Xendit payment link
  window.open("https://checkout.xendit.co/od/ccmhpp", "_blank");
}

/* ===========================
   Certificate Generation
   =========================== */
function generateCertificate() {
  const canvas = document.getElementById("certificateCanvas");
  const ctx = canvas.getContext("2d");

  const fullName = localStorage.getItem("fullName") || "Juan Dela Cruz";
  const verificationCode = localStorage.getItem("verificationCode") || "N/A";

  // Simple certificate rendering
  ctx.fillStyle = "#fff";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  ctx.fillStyle = "#007bff";
  ctx.font = "bold 40px Arial";
  ctx.textAlign = "center";
  ctx.fillText("Certificate of Completion", canvas.width / 2, 200);

  ctx.fillStyle = "#333";
  ctx.font = "28px Arial";
  ctx.fillText(fullName, canvas.width / 2, 350);

  ctx.font = "20px Arial";
  ctx.fillText("Verification Code: " + verificationCode, canvas.width / 2, 500);

  document.getElementById("verificationCode").innerText = verificationCode;

  // Generate QR Code
  const qrContainer = document.getElementById("qrCodeContainer");
  qrContainer.innerHTML = ""; // clear previous QR
  new QRCode(qrContainer, {
    text: verificationCode,
    width: 128,
    height: 128,
    colorDark: "#007bff",
    colorLight: "#ffffff",
    correctLevel: QRCode.CorrectLevel.H
  });
}

function downloadCertificate() {
  const canvas = document.getElementById("certificateCanvas");
  const link = document.createElement("a");
  link.download = "certificate.png";
  link.href = canvas.toDataURL();
  link.click();
}

/* ===========================
   Verification Logic
   =========================== */
function verifyCertificate() {
  const enteredCode = document.getElementById("verifyCode").value.trim().toUpperCase();
  const storedCode = (localStorage.getItem("verificationCode") || "").toUpperCase();

  if (enteredCode === storedCode && enteredCode !== "") {
    document.getElementById("verificationResult").innerText = "✅ Certificate verified successfully!";
    document.getElementById("verificationResult").style.color = "green";
  } else {
    document.getElementById("verificationResult").innerText = "❌ Invalid verification code.";
    document.getElementById("verificationResult").style.color = "red";
  }
}

/* ===========================
   Auto-trigger certificate generation after payment
   =========================== */
document.addEventListener("DOMContentLoaded", function() {
  const certGen = document.getElementById("certificateGeneration");
  if (certGen && !certGen.classList.contains("hidden")) {
    generateCertificate();
  }
});

